// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: topsql_agent.proto

package tipb

import (
	"fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"

	io "io"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CollectCPUTimeRequest struct {
	SqlDigest      []byte   `protobuf:"bytes,1,opt,name=sql_digest,json=sqlDigest,proto3" json:"sql_digest,omitempty"`
	PlanDigest     []byte   `protobuf:"bytes,2,opt,name=plan_digest,json=planDigest,proto3" json:"plan_digest,omitempty"`
	TimestampList  []uint64 `protobuf:"varint,10,rep,packed,name=timestamp_list,json=timestampList" json:"timestamp_list,omitempty"`
	CpuTimeMsList  []uint32 `protobuf:"varint,11,rep,packed,name=cpu_time_ms_list,json=cpuTimeMsList" json:"cpu_time_ms_list,omitempty"`
	NormalizedSql  string   `protobuf:"bytes,20,opt,name=normalized_sql,json=normalizedSql,proto3" json:"normalized_sql,omitempty"`
	NormalizedPlan string   `protobuf:"bytes,21,opt,name=normalized_plan,json=normalizedPlan,proto3" json:"normalized_plan,omitempty"`
	IsInternalSql  bool     `protobuf:"varint,22,opt,name=is_internal_sql,json=isInternalSql,proto3" json:"is_internal_sql,omitempty"`
}

func (m *CollectCPUTimeRequest) Reset()         { *m = CollectCPUTimeRequest{} }
func (m *CollectCPUTimeRequest) String() string { return proto.CompactTextString(m) }
func (*CollectCPUTimeRequest) ProtoMessage()    {}
func (*CollectCPUTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTopsqlAgent, []int{0}
}

func (m *CollectCPUTimeRequest) GetSqlDigest() []byte {
	if m != nil {
		return m.SqlDigest
	}
	return nil
}

func (m *CollectCPUTimeRequest) GetPlanDigest() []byte {
	if m != nil {
		return m.PlanDigest
	}
	return nil
}

func (m *CollectCPUTimeRequest) GetTimestampList() []uint64 {
	if m != nil {
		return m.TimestampList
	}
	return nil
}

func (m *CollectCPUTimeRequest) GetCpuTimeMsList() []uint32 {
	if m != nil {
		return m.CpuTimeMsList
	}
	return nil
}

func (m *CollectCPUTimeRequest) GetNormalizedSql() string {
	if m != nil {
		return m.NormalizedSql
	}
	return ""
}

func (m *CollectCPUTimeRequest) GetNormalizedPlan() string {
	if m != nil {
		return m.NormalizedPlan
	}
	return ""
}

func (m *CollectCPUTimeRequest) GetIsInternalSql() bool {
	if m != nil {
		return m.IsInternalSql
	}
	return false
}

type CollectCPUTimeResponse struct {
}

func (m *CollectCPUTimeResponse) Reset()         { *m = CollectCPUTimeResponse{} }
func (m *CollectCPUTimeResponse) String() string { return proto.CompactTextString(m) }
func (*CollectCPUTimeResponse) ProtoMessage()    {}
func (*CollectCPUTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorTopsqlAgent, []int{1}
}

func init() {
	proto.RegisterType((*CollectCPUTimeRequest)(nil), "tipb.CollectCPUTimeRequest")
	proto.RegisterType((*CollectCPUTimeResponse)(nil), "tipb.CollectCPUTimeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TopSQLAgent service

type TopSQLAgentClient interface {
	// CollectCPUTime is called periodically (e.g. per minute) to save the in-memory TopSQL records
	CollectCPUTime(ctx context.Context, opts ...grpc.CallOption) (TopSQLAgent_CollectCPUTimeClient, error)
}

type topSQLAgentClient struct {
	cc *grpc.ClientConn
}

func NewTopSQLAgentClient(cc *grpc.ClientConn) TopSQLAgentClient {
	return &topSQLAgentClient{cc}
}

func (c *topSQLAgentClient) CollectCPUTime(ctx context.Context, opts ...grpc.CallOption) (TopSQLAgent_CollectCPUTimeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TopSQLAgent_serviceDesc.Streams[0], c.cc, "/tipb.TopSQLAgent/CollectCPUTime", opts...)
	if err != nil {
		return nil, err
	}
	x := &topSQLAgentCollectCPUTimeClient{stream}
	return x, nil
}

type TopSQLAgent_CollectCPUTimeClient interface {
	Send(*CollectCPUTimeRequest) error
	CloseAndRecv() (*CollectCPUTimeResponse, error)
	grpc.ClientStream
}

type topSQLAgentCollectCPUTimeClient struct {
	grpc.ClientStream
}

func (x *topSQLAgentCollectCPUTimeClient) Send(m *CollectCPUTimeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *topSQLAgentCollectCPUTimeClient) CloseAndRecv() (*CollectCPUTimeResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CollectCPUTimeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TopSQLAgent service

type TopSQLAgentServer interface {
	// CollectCPUTime is called periodically (e.g. per minute) to save the in-memory TopSQL records
	CollectCPUTime(TopSQLAgent_CollectCPUTimeServer) error
}

func RegisterTopSQLAgentServer(s *grpc.Server, srv TopSQLAgentServer) {
	s.RegisterService(&_TopSQLAgent_serviceDesc, srv)
}

func _TopSQLAgent_CollectCPUTime_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TopSQLAgentServer).CollectCPUTime(&topSQLAgentCollectCPUTimeServer{stream})
}

type TopSQLAgent_CollectCPUTimeServer interface {
	SendAndClose(*CollectCPUTimeResponse) error
	Recv() (*CollectCPUTimeRequest, error)
	grpc.ServerStream
}

type topSQLAgentCollectCPUTimeServer struct {
	grpc.ServerStream
}

func (x *topSQLAgentCollectCPUTimeServer) SendAndClose(m *CollectCPUTimeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *topSQLAgentCollectCPUTimeServer) Recv() (*CollectCPUTimeRequest, error) {
	m := new(CollectCPUTimeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TopSQLAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tipb.TopSQLAgent",
	HandlerType: (*TopSQLAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CollectCPUTime",
			Handler:       _TopSQLAgent_CollectCPUTime_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "topsql_agent.proto",
}

func (m *CollectCPUTimeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CollectCPUTimeRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.SqlDigest) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTopsqlAgent(dAtA, i, uint64(len(m.SqlDigest)))
		i += copy(dAtA[i:], m.SqlDigest)
	}
	if len(m.PlanDigest) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTopsqlAgent(dAtA, i, uint64(len(m.PlanDigest)))
		i += copy(dAtA[i:], m.PlanDigest)
	}
	if len(m.TimestampList) > 0 {
		dAtA2 := make([]byte, len(m.TimestampList)*10)
		var j1 int
		for _, num := range m.TimestampList {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0x52
		i++
		i = encodeVarintTopsqlAgent(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if len(m.CpuTimeMsList) > 0 {
		dAtA4 := make([]byte, len(m.CpuTimeMsList)*10)
		var j3 int
		for _, num := range m.CpuTimeMsList {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		dAtA[i] = 0x5a
		i++
		i = encodeVarintTopsqlAgent(dAtA, i, uint64(j3))
		i += copy(dAtA[i:], dAtA4[:j3])
	}
	if len(m.NormalizedSql) > 0 {
		dAtA[i] = 0xa2
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintTopsqlAgent(dAtA, i, uint64(len(m.NormalizedSql)))
		i += copy(dAtA[i:], m.NormalizedSql)
	}
	if len(m.NormalizedPlan) > 0 {
		dAtA[i] = 0xaa
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintTopsqlAgent(dAtA, i, uint64(len(m.NormalizedPlan)))
		i += copy(dAtA[i:], m.NormalizedPlan)
	}
	if m.IsInternalSql {
		dAtA[i] = 0xb0
		i++
		dAtA[i] = 0x1
		i++
		if m.IsInternalSql {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *CollectCPUTimeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CollectCPUTimeResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeVarintTopsqlAgent(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CollectCPUTimeRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.SqlDigest)
	if l > 0 {
		n += 1 + l + sovTopsqlAgent(uint64(l))
	}
	l = len(m.PlanDigest)
	if l > 0 {
		n += 1 + l + sovTopsqlAgent(uint64(l))
	}
	if len(m.TimestampList) > 0 {
		l = 0
		for _, e := range m.TimestampList {
			l += sovTopsqlAgent(uint64(e))
		}
		n += 1 + sovTopsqlAgent(uint64(l)) + l
	}
	if len(m.CpuTimeMsList) > 0 {
		l = 0
		for _, e := range m.CpuTimeMsList {
			l += sovTopsqlAgent(uint64(e))
		}
		n += 1 + sovTopsqlAgent(uint64(l)) + l
	}
	l = len(m.NormalizedSql)
	if l > 0 {
		n += 2 + l + sovTopsqlAgent(uint64(l))
	}
	l = len(m.NormalizedPlan)
	if l > 0 {
		n += 2 + l + sovTopsqlAgent(uint64(l))
	}
	if m.IsInternalSql {
		n += 3
	}
	return n
}

func (m *CollectCPUTimeResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func sovTopsqlAgent(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTopsqlAgent(x uint64) (n int) {
	return sovTopsqlAgent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CollectCPUTimeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTopsqlAgent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CollectCPUTimeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CollectCPUTimeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SqlDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopsqlAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTopsqlAgent
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SqlDigest = append(m.SqlDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.SqlDigest == nil {
				m.SqlDigest = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlanDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopsqlAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTopsqlAgent
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlanDigest = append(m.PlanDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.PlanDigest == nil {
				m.PlanDigest = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTopsqlAgent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.TimestampList = append(m.TimestampList, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTopsqlAgent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTopsqlAgent
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTopsqlAgent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.TimestampList = append(m.TimestampList, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampList", wireType)
			}
		case 11:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTopsqlAgent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.CpuTimeMsList = append(m.CpuTimeMsList, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTopsqlAgent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTopsqlAgent
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTopsqlAgent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.CpuTimeMsList = append(m.CpuTimeMsList, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field CpuTimeMsList", wireType)
			}
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NormalizedSql", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopsqlAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopsqlAgent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NormalizedSql = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NormalizedPlan", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopsqlAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopsqlAgent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NormalizedPlan = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsInternalSql", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopsqlAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsInternalSql = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTopsqlAgent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTopsqlAgent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CollectCPUTimeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTopsqlAgent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CollectCPUTimeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CollectCPUTimeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTopsqlAgent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTopsqlAgent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTopsqlAgent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTopsqlAgent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTopsqlAgent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTopsqlAgent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTopsqlAgent
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTopsqlAgent
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTopsqlAgent(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTopsqlAgent = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTopsqlAgent   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("topsql_agent.proto", fileDescriptorTopsqlAgent) }

var fileDescriptorTopsqlAgent = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xd1, 0x4e, 0xf2, 0x30,
	0x18, 0x86, 0x29, 0x90, 0x3f, 0x3f, 0x1f, 0x0e, 0x4c, 0x03, 0x64, 0x41, 0x9d, 0x0b, 0x09, 0x32,
	0x4f, 0x66, 0xa2, 0x57, 0xa0, 0x78, 0x62, 0x82, 0x11, 0x07, 0x9e, 0xba, 0x8c, 0xd1, 0x2c, 0x4d,
	0xba, 0xb6, 0xa3, 0xe5, 0xc4, 0x2b, 0xf1, 0xcc, 0xdb, 0xf1, 0xd0, 0x4b, 0x30, 0x78, 0x23, 0xa6,
	0x05, 0x15, 0x0d, 0x67, 0xcb, 0xf3, 0x3e, 0x7b, 0xf3, 0xe5, 0x2d, 0x60, 0x2d, 0xa4, 0x2a, 0x58,
	0x9c, 0x64, 0x84, 0xeb, 0x50, 0x2e, 0x84, 0x16, 0xb8, 0xaa, 0xa9, 0x9c, 0x75, 0x5b, 0x99, 0xc8,
	0x84, 0x05, 0x67, 0xe6, 0x6b, 0x9d, 0xf5, 0x5e, 0xca, 0xd0, 0x1e, 0x0a, 0xc6, 0x48, 0xaa, 0x87,
	0xe3, 0x87, 0x29, 0xcd, 0x49, 0x44, 0x8a, 0x25, 0x51, 0x1a, 0x1f, 0x01, 0x98, 0xa2, 0x39, 0xcd,
	0x88, 0xd2, 0x2e, 0xf2, 0x51, 0xb0, 0x17, 0xd5, 0x54, 0xc1, 0xae, 0x2d, 0xc0, 0xc7, 0x50, 0x97,
	0x2c, 0xe1, 0x5f, 0x79, 0xd9, 0xe6, 0x60, 0xd0, 0x46, 0xe8, 0x43, 0x43, 0xd3, 0x9c, 0x28, 0x9d,
	0xe4, 0x32, 0x66, 0x54, 0x69, 0x17, 0xfc, 0x4a, 0x50, 0x8d, 0x9c, 0x6f, 0x3a, 0xa2, 0x4a, 0xe3,
	0x01, 0xec, 0xa7, 0x72, 0x19, 0x1b, 0x18, 0xe7, 0x6a, 0x2d, 0xd6, 0xfd, 0x4a, 0xe0, 0x44, 0x4e,
	0x2a, 0x97, 0xe6, 0xa0, 0x5b, 0x65, 0xc5, 0x3e, 0x34, 0xb8, 0x58, 0xe4, 0x09, 0xa3, 0x4f, 0x64,
	0x1e, 0xab, 0x82, 0xb9, 0x2d, 0x1f, 0x05, 0xb5, 0xc8, 0xf9, 0xa1, 0x93, 0x82, 0xe1, 0x01, 0x34,
	0xb7, 0x34, 0x73, 0x8f, 0xdb, 0xb6, 0xde, 0xd6, 0xdf, 0x63, 0x96, 0x70, 0x7c, 0x02, 0x4d, 0xaa,
	0x62, 0xca, 0x35, 0x59, 0xf0, 0x84, 0xd9, 0xc2, 0x8e, 0x8f, 0x82, 0xff, 0x91, 0x43, 0xd5, 0xcd,
	0x86, 0x4e, 0x0a, 0xd6, 0x73, 0xa1, 0xf3, 0x77, 0x20, 0x25, 0x05, 0x57, 0xe4, 0xfc, 0x11, 0xea,
	0x53, 0x21, 0x27, 0xf7, 0xa3, 0x4b, 0x33, 0x36, 0xbe, 0x83, 0xc6, 0x6f, 0x11, 0x1f, 0x84, 0x66,
	0xf9, 0x70, 0xe7, 0xbe, 0xdd, 0xc3, 0xdd, 0xe1, 0xba, 0xbb, 0x57, 0x0a, 0xd0, 0xd5, 0xe9, 0xeb,
	0xca, 0x43, 0x6f, 0x2b, 0x0f, 0xbd, 0xaf, 0x3c, 0xf4, 0xfc, 0xe1, 0x95, 0xa0, 0x9d, 0x8a, 0x3c,
	0x94, 0x94, 0x67, 0x69, 0x22, 0x43, 0x4d, 0xe7, 0x33, 0xdb, 0x31, 0x46, 0xb3, 0x7f, 0xf6, 0x35,
	0x2f, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x04, 0x87, 0x43, 0xaa, 0xff, 0x01, 0x00, 0x00,
}
